### ISSUE TITLE
MAC Address Lookup (OSX)

### ISSUE THREAD

**Issue by chuyskywalker** [Fabian-Schmidt/esphome-victron_ble#10]
I had a **devil** of a time setting this up because the commands on the linked victron python page (which interact with the sqlite database) on OSX return some weird uuid like looking code for "mac address". This code, however, is NOT a mac address and the esphome yaml rejects it.

Instead, [based on this insight](https://apple.stackexchange.com/questions/336264/command-line-to-find-bluetooth-devices-mac-address) i found you could run the command:

```
system_profiler SPBluetoothDataType
```

Which *does* list the right style mac address. It would be useful to mention this in the instructions.

**Comment by Fabian-Schmidt** [comment]
I don't have access to any Macintosh OS devices.

Can you provide a quick guide/steps so I can add them?

**Comment by chuyskywalker** [comment]
After installing the Victron app so that I could extract the key (as per the instructions), I just opened the `terminal.app` program and ran the command above. In the output from that command the Victron Bluetooth item shows up along with it's (legitimate) mac address.

**Comment by whatdoesthatdo** [comment]
I had the same issue on OSX when trying to get the mac address but the following command when run in the Terminal will give you the mac address and bindkey.

```shell
sqlite3 ~/Library/Containers/com.victronenergy.victronconnect.mac/Data/Library/Application\ Support/Victron\ Energy/Victron\ Connect/d25b6546b47ebb21a04ff86a2c4fbb76.sqlite 'select macAddress, advertisementKey from advertisementKeys'
```

**Comment by ErikThiart** [comment]
+1 wasted hours on this.

Wish I knew about `system_profiler SPBluetoothDataType` sooner

**Comment by Fabian-Schmidt** [comment]
Readme updated with more details for obtaining mac and key.
