### ISSUE TITLE
Fehlende Werte 

### ISSUE THREAD

**Issue by Garfs-Homassistant** [Fabian-Schmidt/esphome-victron_ble#16]
Hallo, 

kann für die mppts noch folgendes aufgenommen 

- yield total
- yield yesterday

Danke

**Comment by Fabian-Schmidt** [comment]
Hi,

`Yield Total` and `Yield Yesterday` are not part of the Victron Bluetooth advertising protocol.

See <https://community.victronenergy.com/storage/attachments/48745-extra-manufacturer-data-2022-12-14.pdf> page 3.

**Comment by Garfs-Homassistant** [comment]
Ok, schade

danke für die Info
