### ISSUE TITLE
Panel Voltage (PV Voltage) missing

### ISSUE THREAD

**Issue by enricgmd** [Fabian-Schmidt/esphome-victron_ble#19]
Hi, first of all thank you for your work, you saved me a lot of hours and effort. It works really well!
There's one thing that is quite important that I think is missing, though:
There's no way (or at least I didn't found) to retrieve the PV Voltage (voltage of the solar panels). There's no such option in sensors, and the SmartSolar Charger is indeed transmitting that value. Could it be possible to integrate it to an upcoming update?Thrank you!

**Comment by Fabian-Schmidt** [comment]
Hi,

`PV Voltage` is not part of the Victron Bluetooth advertising protocol.

See <https://community.victronenergy.com/storage/attachments/48745-extra-manufacturer-data-2022-12-14.pdf> page 3.
