### ISSUE TITLE
Compatibility - BMV-712

### ISSUE THREAD

**Issue by davewatson91** [Fabian-Schmidt/esphome-victron_ble#24]
Love your work - this is a great solution for those not wanting to physically wire into their units (I have a camper which I would rather not keep an ESP powered on). 

I'm trying to get it going, but not sure on compatibility. I have a BMV-712, which shows up in the app as the screenshots below. It's not on the list explicitly, but (likely wrongly) assumed that given it's compatible with the rest of the Victron BLE gear, that it would be. 

![bmv712-1](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/51277302/b43ef1b8-6e47-470c-983c-1e88299d534f)
![bmv712-2](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/51277302/130cc9d2-ddd7-4d43-b0e7-42e064a47114)

**Comment by Fabian-Schmidt** [comment]
Hi, The BMV-712 is supported. Just use the Instant readout details / Encryption data provided at the bottom of the page.

**Comment by davewatson91** [comment]
Perfect thanks! @Fabian-Schmidt. 

Is there any basic troubleshooting steps I can take as to why I'm getting nothing output when setup like that?

**Comment by Fabian-Schmidt** [comment]
Use the ESP Home logger and check the output. See <https://esphome.io/components/logger> for reference.
Adjust [Log Level](https://esphome.io/components/logger#log-levels) to get more details.

My recommendation is to use the hardware logging. So connected via USB and logging via USB/Serial and via Wifi / Ethernet as this can have significant impact on the outcome.

**Comment by davewatson91** [comment]
Thanks - managed to find some issues - all working now!

**Comment by Fabian-Schmidt** [comment]
Any lessons learned or things which I can add to the readme to help other avoid this issue?

**Comment by davewatson91** [comment]
No, the docs were quite good - it was my own stupidity that caused me dramas (interference causing a crazy low range (<1m) out of the BLE.
