### ISSUE TITLE
SmartLithium Balancer Status

### ISSUE THREAD

**Issue by H3xF2x** [Fabian-Schmidt/esphome-victron_ble#25]
Hello,

for my SmartLithium Batteries I found the following definition for` balancer_status`:

0 - unkonwn (need to charge once to 100%)
1 - balanced / ok
2 - balancing
3 - inbalanced

I hope you find this information useful

H3xF2x

**Comment by Fabian-Schmidt** [comment]
Thanks @H3xF2x for your input.
I have added the balancer status as text sensor.

Can you please validate that it is working correctly?

Thanks

**Comment by H3xF2x** [comment]
You're welcome.

The text sensor is working, thanks for implementing.
Unfortunately at the moment both batteries are balanced, so it could take serveral weeks until one battery needs to be balanced again. I will keep an eye on it.

BTW: The temperature readout on a Lynx BMS returns always a 127 / unknown. Maybe you would like to add a not on this in the readme.

I will try to find more missing details.

**Comment by Fabian-Schmidt** [comment]
I added a validation for the temperature sensor and a node to the readme.
At least ESP Home should report NAN now.

**Comment by H3xF2x** [comment]
I can confirm that the latest update works for me.
