### ISSUE TITLE
powercylce shunt

### ISSUE THREAD

**Issue by riker65** [Fabian-Schmidt/esphome-victron_ble#27]
Hi, 
I do not understand how to powercycle the shunt?

any hint please?

thanks Thomas

**Comment by Fabian-Schmidt** [comment]
To powercycle the shunt you have to disconnect all cable and wait a moment.
Please consult the Victron manual for details.
But why do you want to restart the shunt? Mine is running for months without any issues.

**Comment by riker65** [comment]
Hi Fabian,

mine too, but your instructions in readme said:
Steps

    Use a SmartShunt, other devices don't support this yet.
    Use VictronConnect v5.42 or newer.
    Update the SmartShunt to version v2.31 or later.
    Connect to the SmartShunt using VictronConnect, and enable this protocol (screenshot below)
    Power cycle the SmartShunt
    Use victron_scanner to find mac address of your SmartShunt.


so wondering which steps to do

do I need the passcode  off the app for connection ?

or only mac address , pull from app info and security key?


Thanks Thomas

**Comment by Fabian-Schmidt** [comment]
Ah this step is bad worded. I meant to just to disconnect the app from the device. So it is open for connection from the ESP again.

Sorry for the confusion.

FYI: My recommendation is to use the `victron_ble` component instead of the `victron_ble_connect` for reading data from the shunt.

**Comment by riker65** [comment]
thanks understood

**Comment by riker65** [comment]
closed as clarified
