### ISSUE TITLE
Smart Battery Sense integration

### ISSUE THREAD

**Issue by HaraldWolf** [Fabian-Schmidt/esphome-victron_ble#33]
Hello Fabian,
First of all, thank you very much for the great work. I have a “SmartSolar MPPT 75/15” and a “SmartBatterySense” running. The "SmartSolar" has been running for some time now via "VE.Direct" and an "ESP32" with Homeassiant. Now I would like to put the “SmartBatterySense” into operation. There would probably be no other option than to connect everything via BLE. I already have the “SmartSolar” running successfully via BLE. Could you include the “SmartBatterySense” with its two sensors “Battery Voltage” and “Battery Temperature”?

That would be nice
Harald

**Comment by HBK1** [comment]
Battery Sense is already working:
https://github.com/Fabian-Schmidt/esphome-victron_ble/issues/20

**Comment by HaraldWolf** [comment]
Sorry, I didn't know that
I have entered the sensor, but I get the following error?

[W][victron_ble.sensor:511]: [E1:5B:EE:84:A4:5C] Incorrect Aux input configuration.

**Comment by HaraldWolf** [comment]
Sorry, there was another typo in the encryption key
now it works :)

Many thanks for the support
