### ISSUE TITLE
SmartShunt

### ISSUE THREAD

**Issue by Marcepanfazik** [Fabian-Schmidt/esphome-victron_ble#36]
Hello
I need followig options for my PV instalation:
amount of charged energy
amount of discharged energy
battery SOC
Is it possible?
p.s sorry for my English

**Comment by Fabian-Schmidt** [comment]
A SmartShunt is a Battery monitor. Therefore the following sensor values are available:

- AUX_VOLTAGE in V (1)
- BATTERY_CURRENT in A
- BATTERY_VOLTAGE in V
- BATTERY_POWER in W
- CONSUMED_AH in Ah
- MID_VOLTAGE in V (1)
- STATE_OF_CHARGE in %
- TEMPERATURE in °C (1)
- TIME_TO_GO in minutes

(1) - Available if device aux port is configured. 

The amount of charged and discharged energy is in the field `CONSUMED_AH`.
The battery SOC is in the field `STATE_OF_CHARGE`.

These are all available fields transmitted by the Victron Battery Shunt. I cannot add additional fields.
