### ISSUE TITLE
Victron Muliplus Compact 12/2000/80 120V VE.Bus

### ISSUE THREAD

**Issue by ottoxgam** [Fabian-Schmidt/esphome-victron_ble#37]
Hello, 

I'm trying to integrate my Multiplus Compact through ESP Home to track Wattage, SOC, and Battery Voltage in HA but I keep running into a "Record type 0C message is too short (13)" Error. 

`[05:13:22][VV][scheduler:032]: set_timeout(name='VictronBle0', timeout=0)`

`[05:13:22][VV][esp32_ble_tracker:423]: Parse Result:`

`[05:13:22][VV][esp32_ble_tracker:440]:   Address: CB:53:E9:0F:D7:12 (RANDOM)`

`[05:13:22][VV][esp32_ble_tracker:442]:   RSSI: -56`

`[05:13:22][VV][esp32_ble_tracker:443]:   Name: 'VE.Bus Smart HQ213322AJ4'`

`[05:13:22][VV][esp32_ble_tracker:451]:   Ad Flag: 6`

`[05:13:22][VV][esp32_ble_tracker:457]:   Manufacturer data: 10.03.08.27.0C.1C.3F.69.28.CF.7F.C4.CD.6A.A2.D3.FF.85.EB.DB.ED (21)`

`[05:13:22][VV][esp32_ble_tracker:473]: Adv data: 02.01.06.18.FF.E1.02.10.03.08.27.0C.1C.3F.69.28.CF.7F.C4.CD.6A.A2.D3.FF.85.EB.DB.ED.19.09.56.45.2E.42.75.73.20.53.6D.61.72.74.20.48.51.32.31.33.33.32.32.41.4A.34 (54)`

`[05:13:22][VV][victron_ble:152]: [CB:53:E9:0F:D7:12] Cryted message: 28.CF.7F.C4.CD.6A.A2.D3.FF.85.EB.DB.ED (13)`

`[05:13:22][W][victron_ble:271]: [CB:53:E9:0F:D7:12] Record type 0C message is too short (13).`

**Comment by Fabian-Schmidt** [comment]
Hi @ottoxgam,
I think I copied a wrong type from the victron PDF.

Can you please validate that it is working correctly?

You might need to include `refresh: 0s` to the `external_components` to ensure it loads the updated version.

**Comment by ottoxgam** [comment]
Hello! Thanks for making the change! I am seeing data flow through, however have received a new error regarding "AC Current In"

`[20:20:57][V][esp32_ble:314]: (BLE) gap_event_handler - 3`
`[20:20:57][VV][esp32_ble_tracker:423]: Parse Result:`
`[20:20:57][VV][esp32_ble_tracker:440]:   Address: CB:53:E9:0F:D7:12 (RANDOM)`
`[20:20:57][VV][esp32_ble_tracker:442]:   RSSI: -58`
`[20:20:57][VV][esp32_ble_tracker:443]:   Name: 'VE.Bus Smart HQ213322AJ4'`
`[20:20:57][VV][esp32_ble_tracker:451]:   Ad Flag: 6`
`[20:20:57][VV][esp32_ble_tracker:457]:   Manufacturer data:` `10.03.08.27.0C.FF.60.69.86.12.60.64.BF.9F.87.D7.9F.EC.33.0A.4B (21)`
`[20:20:57][VV][esp32_ble_tracker:473]: Adv data:` `02.01.06.18.FF.E1.02.10.03.08.27.0C.FF.60.69.86.12.60.64.BF.9F.87.D7.9F.EC.33.0A.4B.19.09.56.45.2E.42.75.73.20.53.6D.61.``72.74.20.48.51.32.31.33.33.32.32.41.4A.34 (54)`
`[20:20:57][VV][victron_ble:152]: [CB:53:E9:0F:D7:12] Cryted message: 86.12.60.64.BF.9F.87.D7.9F.EC.33.0A.4B (13)`
`[20:20:57][V][victron_ble:204]: [CB:53:E9:0F:D7:12] Enrypted message: 05.00.01.00.45.05.9D.02.A0.14.00.41.F2 (13)`
`[20:20:57][D][victron_ble:356]: [CB:53:E9:0F:D7:12] Recieved VE_BUS message.`
`[20:20:57][VV][scheduler:032]: set_timeout(name='VictronBle0', timeout=0)`
`[20:20:57][VV][scheduler:032]: set_timeout(name='VictronBleC', timeout=0)`
`[20:20:57][W][component:214]: Component esp32_ble_tracker took a long time for an operation (0.10 s).`
`[20:20:57][W][component:215]: Components should block for at most 20-30ms.`
`[20:20:57][VV][scheduler:226]: Running timeout 'VictronBle0' with interval=0 last_execution=112401 (now=112446)`
`[20:20:57][V][sensor:043]: 'AC Power IN': Received new state 669.000000`
`[20:20:57][D][sensor:094]: 'AC Power IN': Sending state 669.00000 W with 0 decimals of accuracy`
`[20:20:57][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {`
 ` key: 1853764123`
 ` state: 669`
 ` missing_state: NO`
`}`
`[20:20:57][V][sensor:043]: 'AC Power OUT': Received new state 660.000000`
`[20:20:57][D][sensor:094]: 'AC Power OUT': Sending state 660.00000 W with 0 decimals of accuracy`
`[20:20:57][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {`
 ` key: 4103816374`
 ` state: 660`
 ` missing_state: NO`
`}`
`[20:20:57][W][victron_ble.sensor:071]: [CB:53:E9:0F:D7:12] Device has no 'ac current' field.`
`[20:20:57][V][sensor:043]: 'AC current': Received new state nan`
`[20:20:57][D][sensor:094]: 'AC current': Sending state nan A with 1 decimals of accuracy`
`[20:20:57][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {`
 ` key: 1369225267`
 ` state: nan`
 ` missing_state: NO`
`}`
`[20:20:57][W][component:214]: Component victron_ble took a long time for an operation (0.11 s).`
`[20:20:57][W][component:215]: Components should block for at most 20-30ms.`
`[20:20:57][VV][scheduler:226]: Running timeout 'VictronBleC' with interval=0 last_execution=112406 (now=112446)`

**Comment by ottoxgam** [comment]
Everything is looking good on my end! Thanks for the update!

**Comment by Fabian-Schmidt** [comment]
> Everything is looking good on my end! Thanks for the update!

That's great to hear.

Can you assist me with some testing with the Multiplus as I don't have access to such a device.

I am missing some information for the fields `ERROR` and `DEVICE_STATE`.

Can you please report some values and what the representation within the Victron App is?

**Comment by ottoxgam** [comment]
Absolutely! I'll have to re-patch the inverter to the VE.Bus cable when I get home this evening. 
I have noticed that the SOC from the multiplus seems to be formatted wrong. Photo attached. 
<img width="1083" alt="Screen Shot 2023-12-23 at 5 18 13 PM" src="https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/87922/7833643a-833a-49cf-a04a-fee35e8e6a5b">

**Comment by Fabian-Schmidt** [comment]
I changed the sensor reading of SOC. This should fix the issue.

**Comment by ottoxgam** [comment]
absorbtion Charge:
[13:08:52][VV][esp32_ble_tracker:457]:   Manufacturer data: 10.03.08.27.0C.12.E9.69.D6.59.8A.43.0E.9B.6A.44.22.5A.CF.4D.38 (21)
[13:08:52][VV][esp32_ble_tracker:473]: Adv data: 02.01.06.18.FF.E1.02.10.03.08.27.0C.12.E9.69.D6.59.8A.43.0E.9B.6A.44.22.5A.CF.4D.38.19.09.56.45.2E.42.75.73.20.53.6D.61.72.74.20.48.51.32.31.33.33.32.32.41.4A.34 (54)
[13:08:52][VV][victron_ble:152]: [CB:53:E9:0F:D7:12] Cryted message: D6.59.8A.43.0E.9B.6A.44.22.5A.CF.4D.38 (13)
[13:08:52][V][victron_ble:204]: [CB:53:E9:0F:D7:12] Enrypted message: 04.00.00.00.99.05.BC.02.B0.15.00.40.F2 (13)


Inverting:
[13:09:38][VV][esp32_ble_tracker:457]:   Manufacturer data: 10.03.08.27.0C.3F.E9.69.BA.2C.81.23.99.F7.28.BA.D7.55.21.67.33 (21)
[13:09:38][VV][esp32_ble_tracker:473]: Adv data: 02.01.06.18.FF.E1.02.10.03.08.27.0C.3F.E9.69.BA.2C.81.23.99.F7.28.BA.D7.55.21.67.33.19.09.56.45.2E.42.75.73.20.53.6D.61.72.74.20.48.51.32.31.33.33.32.32.41.4A.34 (54)
[13:09:38][VV][victron_ble:152]: [CB:53:E9:0F:D7:12] Cryted message: BA.2C.81.23.99.F7.28.BA.D7.55.21.67.33 (13)
[13:09:38][V][victron_ble:204]: [CB:53:E9:0F:D7:12] Enrypted message: 09.00.E4.FD.69.85.00.00.88.15.00.40.F2 (13)

Once the battery gets back to float, I can get you those as well.
