### ISSUE TITLE
victron energy blue smart ip65 charger support

### ISSUE THREAD

**Issue by cop98** [Fabian-Schmidt/esphome-victron_ble#38]
Hello,

Is there support for victron energy blue smart ip65 charger?

Eventually, I am available for any test

Thank you

**Comment by Fabian-Schmidt** [comment]
Looks like the blue smart ip65 charger does not support instant readout. <https://www.victronenergy.com/media/pg/VictronConnect_Manual/en/stored-trends---instant-readout.html#UUID-5eec18d4-9e11-0845-47e5-9a8f0cec49f4>

This component is using the instant readout feature. If the victron device does not support it than there is nothing I can do.
