### ISSUE TITLE
Enhancement Request- 

### ISSUE THREAD

**Issue by dougle03** [Fabian-Schmidt/esphome-victron_ble#41]
Would be good to add in a template sensor for shunt Watts. (AxV) into your standard full yaml?
Perhaps something like this?
Note: Requires id's adding to both Amps and Volts sensors.

`  - platform: template
    name: "Watts"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    icon: "mdi:flash"
    lambda: |-
      return id(amps).state * id(volts).state;`

**Comment by Fabian-Schmidt** [comment]
There is already the field `BATTERY_POWER` which combines `BATTERY_CURRENT` and `BATTERY_VOLTAGE`.

Is this the Watt value you are referring to?

If not can you please share more of your configuration? As I don't know which fields the id amps and volts are referencing.

**Comment by dougle03** [comment]
I'm not seeing that field in my implementation!
The items highlighted by the red line are the only sensors I'm getting from my Shunt via the integration.
![image](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/59865048/ef315455-cc2f-4198-b60a-d9cd4ff4f2f7)
Am I missing some other fields too?

**Comment by Fabian-Schmidt** [comment]
If you check the configured sensors in ESP Home you should have a `BATTERY_CURRENT` and `BATTERY_VOLTAGE` field. Just add add a `BATTERY_POWER`. From a technical side it does exactly the same as you do just multiplying the two values.

**Comment by dougle03** [comment]
> If you check the configured sensors in ESP Home you should have a `BATTERY_CURRENT` and `BATTERY_VOLTAGE` field. Just add add a `BATTERY_POWER`. From a technical side it does exactly the same as you do just multiplying the two values.

Thanks for this. I did use the full.yaml as my template, so not sure how I missed this. Thanks again.
