### ISSUE TITLE
Q: Why is my 'consumed ah' a negative value

### ISSUE THREAD

**Issue by dougle03** [Fabian-Schmidt/esphome-victron_ble#42]
Hi, great project and really useful.
Just a question:
Is my consumed ah reading a negative value correct?
![image](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/59865048/5cba6d4b-7486-44e0-9156-f4bc020c1a24)

**Comment by Fabian-Schmidt** [comment]
As it is consumed Ah it is always negative and will never be positive. It is the same as the Victron App.

If you want the value to be positive just add an ESPHome filter to the sensor and multiply the value by `-1`. See https://esphome.io/components/sensor/index.html#multiply

**Comment by dougle03** [comment]
No problems, thanks.
