### ISSUE TITLE
Enhancement request: Toggle BatteryProtect load on/off

### ISSUE THREAD

**Issue by jsmath** [Fabian-Schmidt/esphome-victron_ble#44]
I'm guessing this isn't currently possible, but it would be nice to be able to toggle the BatteryProtect loads on/off like is possible in the Victron App or turn on/ off solar charging with the SmartSolar. Thank you for your time and great work!

**Comment by Fabian-Schmidt** [comment]
Unfortunately this is impossible. The Victron device is only broadcasting the its state similar to the overview page in the Victron App. I never transmit any information to the device, therefore I don't have any option of changing the load.
