### ISSUE TITLE
Multiplus reports sometimes strange wrong values

### ISSUE THREAD

**Issue by naofireblade** [Fabian-Schmidt/esphome-victron_ble#45]
Hi, some times when switched off the Multiplus (VE.BUS) reports 262.143W instead of 0W for ACTIVE_AC_IN_POWER and AC_OUT_POWER. Also the text_sensor DEVICE_STATE  is 255 instead of 'off'.

Other values from the Multiplus like BATTERY_VOLTAGE are correct.

Switching the Multiplus on or to charging only, solves the problem. 

Values on the Cerbo GX are correct at any time.

**Comment by Fabian-Schmidt** [comment]
Thanks for the report. I will look into it on the weekend.

**Comment by Fabian-Schmidt** [comment]
Hi,
I added handling for these cases. The sensor is transmit NAN (Not a number) now.

**Comment by Fabian-Schmidt** [comment]
Is this issue resolved? Can I close it?
