### ISSUE TITLE
Smart Battery Sense - Request

### ISSUE THREAD

**Issue by dougle03** [Fabian-Schmidt/esphome-victron_ble#49]
Hi,
Great integration, thanks.

Any plans to add in the Victron Smart Battery Sense?
I've just fitted one to my van and it's up and running including additional information in the main list.
Shows voltage and temperature.

Thanks

![image](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/59865048/2b590e8f-3d61-48da-8b95-22b0c7ad4716)

**Comment by Fabian-Schmidt** [comment]
Does the Smart Battery Sense have the encryption data in the product info page of the device?
If yes what happens if you configure them?

**Comment by dougle03** [comment]
Hi yes, I've added it to my YAML but I've only copied your example so don't really know what to do.
I've added the MAC and encryption under the entries for the shunt and MPPT, but can't work out how to add in the sensor/s.
Thanks

**Comment by dougle03** [comment]
![image](https://github.com/Fabian-Schmidt/esphome-victron_ble/assets/59865048/c5d3932f-bb26-494f-b589-e1a3506d7a25)

**Comment by HBK1** [comment]
https://github.com/Fabian-Schmidt/esphome-victron_ble/issues/20

**Comment by Fabian-Schmidt** [comment]
I would expect a battery monitor message from the device. So looking at the table i expect a voltage sensor `BATTERY_VOLTAGE` and temperature `TEMPERATURE`.
Can you try these two sensors?

**Comment by dougle03** [comment]
Hi Fabian,
Sorry for the delay, had to get actual access to my Moho as the ESP would not update OTA...
I now have both battery voltage and temperature from the Battery Sense. All working great.
Perhaps update your main table to include the sense?
Thanks for your help, Pete

**Comment by dougle03** [comment]
Works with Voltage and Temperature.
