### ISSUE TITLE
Readout of Victron DC/DC charger Orion XS

### ISSUE THREAD

**Issue by terdt** [Fabian-Schmidt/esphome-victron_ble#50]
I

**Comment by terdt** [comment]
I replaced the Orion-Tr Smart DC/DC by the new Orion XS charger. In the yaml I replaced the mac address and  the encryption key by the Orion XS data. But it's not working out of the box as I expected. What can I do ?

**Comment by Fabian-Schmidt** [comment]
Can you please provide a log from the ESP device?

**Comment by terdt** [comment]
yes, of course, it is a little bit overloaded due to the amount of services which are running on the ESP

[logs_womo-1_logs.txt](https://github.com/Fabian-Schmidt/esphome-victron_ble/files/15405320/logs_womo-1_logs.txt)

**Comment by Fabian-Schmidt** [comment]
> yes, of course, it is a little bit overloaded due to the amount of services which are running on the ESP
> 
> [logs_womo-1_logs.txt](https://github.com/Fabian-Schmidt/esphome-victron_ble/files/15405320/logs_womo-1_logs.txt)
> 

Thanks for the log.
It contains the following message:

```
[W][victron_ble:266]: [xx:xx:xx:xx:xx:xx] Unsupported record type 0F
```

This means victron has not documented this type of device.
As I am not affiliated with Victron I only have access to public resources and to two devices which I purchased myself.
Either ask victron to update the announcement protocol definition to include this new device or we need to guess the data / protocol structure.
This would require a couple of examples and the corresponding data from the app.

Please let me know which way you want to go?

**Comment by Fabian-Schmidt** [comment]
To support the device I will create a separate branch and start writing some stub code.
Afterwards I need some verbose logs from you and the corresponding data displayed in the victron app in the overview page.
As there are only 5 values it should be relative easy.

**Comment by Fabian-Schmidt** [comment]
I added a new branch for Orion XS suport.

Can you please create a new config with minimal components and verbose level. E.g.:

```yaml
external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble@OrionXS

logger:
  level: VERBOSE
```

To add support for the device I need a few example values from the log. There should be a message `Encrypted message: `.
And the corresponding value displayed in the Victron App. To identify the various states (Zustände) I need an example for each one. As none of the values can be negative 4-5 examples should be enough. It would be great if the Input and Output (Eingang und Ausgang) have a larger voltage difference (at least 0.5V) to make it easier to find them.

Thanks

**Comment by terdt** [comment]
Please find attached some data. Hopeful it is enough for evaluation. Otherwise I have to see how to log data during driving.

[Victron_log.csv](https://github.com/Fabian-Schmidt/esphome-victron_ble/files/15447850/Victron_log.csv)

**Comment by Fabian-Schmidt** [comment]
Hi,
I added support can you please test?

To ensure you get the latest version please use the following external reference:

```yaml
external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble@OrionXS
    refresh: 0s
```

I added two additional sensor types to support the device `OUTPUT_CURRENT` and `INPUT_CURRENT`.
The device supports the following sensor types:

- `DEVICE_STATE`
- `CHARGER_ERROR`
- `OUTPUT_VOLTAGE`
- `OUTPUT_CURRENT`
- `INPUT_VOLTAGE`
- `INPUT_CURRENT`
- `OFF_REASON`

Can you please test and let me know if it is working.

Cheers,
Fabian

**Comment by terdt** [comment]
Hi Fabian, test passed successful. Thanks a lot. Will you include as standard ? Kind Regards Thomas

**Comment by Fabian-Schmidt** [comment]
Yes I will include it as standard. In a few days I will review the code changes and then merge it.

Have you tested all the sensor types and they present correct values?

**Comment by terdt** [comment]
I have not compared all digits behind the comma, but in general all sensors reflects the values in the App. The text sensors are in English but this is also normal
