### ISSUE TITLE
MPPT - Panel Voltage

### ISSUE THREAD

**Issue by dandrzejewski** [Fabian-Schmidt/esphome-victron_ble#53]
It would be nice to have a sensor reporting the voltage of the PV panel itself.

**Comment by Fabian-Schmidt** [comment]
Indeed it would be nice.

Unfortunately the Victron advertising/announcement protocol does not contain these fields.

I get the same fields which you can see in the Victron app on the Overview page.

See [Victron Community](https://community.victronenergy.com/questions/187303/victron-bluetooth-advertising-protocol.html) for details of the Victron Bluetooth advertising protocol and to ask Victron to include these information.
