### ISSUE TITLE
Sustain DEVICE_STATE for Multiplus-II using VE.Bus

### ISSUE THREAD

**Issue by Algid** [Fabian-Schmidt/esphome-victron_ble#55]
Recently Victron added support for a Sustain function for the Multiplus-II and it seems the DEVICE_STATE text field does not currently support this.

The device state is 244 as seen in the logs:
```
[12:18:01][W][victron_ble.text_sensor:297]: [EE:7F:E7:30:EC:43] Unknown device state (244).
```

In the Victron app I see this as "Sustain".

Thanks for your work on this great project!

**Comment by Fabian-Schmidt** [comment]
Can you please validate the additional device state works?

**Comment by Algid** [comment]
Yes that seems to work perfectly, thanks!
