### ISSUE TITLE
more then one solarcharger possible?

### ISSUE THREAD

**Issue by Oldie-driver** [Fabian-Schmidt/esphome-victron_ble#56]
was nice, if i can use more then one solarcharger. Using just one eps32 für every solarcharger ist not a good option.

My first quick try work with bad side effects.

I would have to derive an object from the class victron_ble for each charge controller, like victron_ble_id and victron_ble_id1. 
But I have no idea how to phrase that.

Is there a solution for this in ESPhome, or do I have to try a new fork?

**Comment by Fabian-Schmidt** [comment]
I have connected 3 solar charger and one shunt to one esp32. What is your issue in doing it? Can you share your config?

**Comment by Oldie-driver** [comment]
The problem is in the energie dashboard.

i make a try in this wrong config way:

victron_ble:
  - id: MySmartSolar
    mac_address: ${smart_solar_mac_address}
    bindkey: ${smart_solar_encryption_key}
  - id: MySmartSolar1
    mac_address: ${smart_solar_mac_address1}
    bindkey: ${smart_solar_encryption_key1}

 - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Yield Today"
    type: YIELD_TODAY

....

 - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Yield Today"
    type: YIELD_TODAY


The field YIELD_TODAY make the Problem in the energie dashboard

In the overview dashbord, the values ​​of the charge controllers are shown alternately. But it looks as if it is the same device with alternating different data.

This make a problem in the energie dashboard. Charger one maybe have Yield_today 100W, charger tow have 600W as example

HA see, Yield_today 100W, then 600W. HA mean, 500W in this few seconds after see 100W, ok, is now only 100W, ignore. Then 600W see again, 500W more, count this again. Around every 20 seconds HA think, i got 500W ~ 3~4x in min, 60 min on a hour.
So see around 900kWh in one hour.  

In any case, on raining afternoon, the energie dashboard say, i got more electric power, then i need in one full year with 2 people.

I need for evey charger at last for YIELD_TODAY a unique entity. I have no idea, how i make this in the yaml config, inside c++ is very easy.

(Sorry, English is not my native language )

**Comment by Fabian-Schmidt** [comment]
Okay the problem is the energy dashboard in HA and not the integration. I don't use / have any HA running. I use ESPHome without HA. 
You can try aggregating the values on the esp. So for HA it is presented as one value.

**Comment by Oldie-driver** [comment]
i am so stuppid, maybe just to old.....
The solution:
The variable names simply need to be renamed

As an example:

 - id: MySmartSolar
    mac_address: ${smart_solar_mac_address}
    bindkey: ${smart_solar_encryption_key}
  - id: MySmartSolar1
    mac_address: ${smart_solar_mac_address1}
    bindkey: ${smart_solar_encryption_key1}
.....
 - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Yield Today"
    type: YIELD_TODAY
....
 - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Battery Voltage1"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Battery Current1"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmartSolar1
    name: "Yield Today1"
    type: YIELD_TODAY
.....

So Home Assistant see both and can work with this. Maybe as an example Yaml Config file or just a hint in the readme ?
