### ISSUE TITLE
Problems adding shunt:   "Bind key must be format XX."   (31 character AES key)

### ISSUE THREAD

**Issue by irrwitzer42** [Fabian-Schmidt/esphome-victron_ble#59]
Hi guys,

first of all: thank you so much for your work!!!

I'm using victron_ble and have so with a bluetooth dongled bluesolar MPPT for some time now.
Today I wanted to add a shunt for better battery monitoring, but when adding it to  the esp config it errors out "Failed config" and "Bind key must be format XX."

So, the error message doesn't give the required format, but I realized,  that the shunt's AES key is exactly one character shorter than the bluesolar AES key.
I tried prefixing the short one with "0", that won't work the error message again, but it won't work either. It even brings the ESP in some kind of faulty state, responding to HTTP shortly resulting in sensor_failed messages, but it doesn't get any values. Neither from the shunt, nor from the mppt.

So. what's wrong here? is the AES key of my shunt "faulty", or how can I get victron_ble to accept the 31 character key?

Thanks in advance and best regards!

   Irrwitzer

**Comment by HBK1** [comment]
My keys for shunt, solar, dcdc and battsense is all 32 char long.

**Comment by irrwitzer42** [comment]
I double checked and made to photos…. my shunt has just 31 characters….
That’s why I assumed, that maybe victron removes the prefixing 0 as it thinks its numbers or something like that.

I think it’s a bug in victron connect (iOS), but in the “instant readout encryption data” dialog, it only displays 31 chars:

**Comment by irrwitzer42** [comment]
Okay, never mind, sorry for bothering you...
I reset the AES key (by changing  the PIN), now it's 32 chars long and config is working ;-)
It still dies after booting.... but that I will have to debug more in depth.

Maybe this might help some other lost soul with 31 char keys...
