### ISSUE TITLE
Smart shunt missing KWH value

### ISSUE THREAD

**Issue by admiralroflknife** [Fabian-Schmidt/esphome-victron_ble#63]
Is there a way to get the kWh value out of the smart shunt? I see it in the app but no entity is there. I’ve tried doing custom sensors but with the update frequency of the data it’s not coming out very accurate compared to the Victron value

**Comment by Fabian-Schmidt** [comment]
Hi, The Victron device typically submits a value every second. But the shunt is known for having a poor antenna. You can try moving the ESP closer to the Victron device or test another device as some ESP have also poor Antennas.

Also depending on the number of other BLE devices you might need to tweak the esphome Bluetooth settings to receive more data.

The kWh can be calculated by multiplying the `CONSUMED_AH` with the nominal voltage of the battery. Eg for a 4S LiFePo4 his is 12.6V.

**Comment by admiralroflknife** [comment]
What settings can I adjust in esphome to increase the data? I have 4 Victron devices I’m pulling from with 1 esp. I’d just multiply the battery voltage by the amperage if I could get more frequent data updates.

**Comment by Fabian-Schmidt** [comment]
Multipling battery voltage with Amp can deliver very [fluctuating](https://dict.leo.org/german-english/fluctuating)

**Comment by Fabian-Schmidt** [comment]
Using Battery Voltage multiplied by Amps will result in the current Watt and not Watthour (Wh).

kWh/Wh is the Watt usage over time. I recommend using the nominal battery voltage instead of the current battery voltage as it gives much more realistic and stable values. And multiplying it with the `CONSUMED_AH` from the Smart Shunt.

You can tweak the following ESP Home settings to receive more BLE package in congested areas:

```
esp32_ble_tracker:
  scan_parameters:
    interval: 10ms
    window: 10ms
    active: false
```

**Comment by admiralroflknife** [comment]
After adjusting the update frequency that totally fixed my data input. I’m getting values every 1-2 seconds. I ended up just making a template sensor for the current times the voltage to create the watts then made an integration sensor that converts that to kWh. It seems to correlate with what I’m seeing in the Victron app. Thank you!
