### ISSUE TITLE
Sun Inverter support

### ISSUE THREAD

**Issue by HansWegman** [Fabian-Schmidt/esphome-victron_ble#65]
Hello Fabian,

I have used your project to successfully integrate my new Sun Inverter, see: https://www.victronenergy.com/upload/documents/Datasheet-Sun-Inverter-EN.pdf.

I am not able to read all parameters though. When activating the victron_scanner it reports nothing so I am in the dark about the type and thus supported sensors.

I have tried quit a few though and came up with the ones listed underneath that work. I am missing a few though as you can see in the attached screenshots which I would like to add. Maybe by forking and adding them to your code so you can merge them?

What can I do to figure this out?

sensor:

  # SunInverter
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Device State"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "AC Apparent Power"
    type: AC_APPARENT_POWER
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "AC Current"
    type: AC_CURRENT
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "AC Voltage"
    type: AC_VOLTAGE
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Sun Inverter Alarm Reason"
    type: ALARM_REASON

binary_sensor:

  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Sun Inverter is in Fault state"
    type: DEVICE_STATE_FAULT
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Sun Inverter has Alarm"
    type: ALARM

text_sensor:

  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Sun Inverter state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: SunInverter
    name: "Sun Inverter Alarm reason"
    type: ALARM_REASON
 
![IMG_1927](https://github.com/user-attachments/assets/7a53073e-2ab0-4abb-bcb9-66d430e51533)
![IMG_1926](https://github.com/user-attachments/assets/dff90db1-59af-4592-b366-22c2aaf5bbc7)

**Comment by HansWegman** [comment]
Thanks for your quick reply Patrick.

What is missing is the "Stroom" (Current) and the "Openklemspanning" (Open circuit voltage). I tried BATTERY_CURRENT and LOAD_CURRENT and both did not work.

**Comment by Fabian-Schmidt** [comment]
Do you see these values on the overview page, before you connect to the device, in the Victron App?

**Comment by HansWegman** [comment]
No sorry, these values are on the main screen when connected, on the overview page are only Battery voltage, AC load and status, see attached.
![IMG_1930](https://github.com/user-attachments/assets/eaf126b5-870d-48b1-bf3c-11786948d71f)

**Comment by Fabian-Schmidt** [comment]
If the information is not shown on the overview page in the victron app then I don't have access to it.
