### ISSUE TITLE
Using a D1 Mini esp8266 with Bluetooth instead of Esp32

### ISSUE THREAD

**Issue by bgbaker** [Fabian-Schmidt/esphome-victron_ble#71]
Hi
Is it possible to use my D1 Mini (esp8266) that has bluetooth support instead of an esp32?
When I tried to just leave the platform and board config pointint to esp8266 the installation fails saying: "Failed config esp32_ble_tracker: [source /config/esphome/victronmonitor.yaml:41] Component esp32_ble_tracker requires component esp32"

**Comment by Fabian-Schmidt** [comment]
The esp8266 does **not** have Bluetooth support.

**Comment by bgbaker** [comment]
Thank you Fabian
