### ISSUE TITLE
Voltage and current values from mppt

### ISSUE THREAD

**Issue by ondrej0402** [Fabian-Schmidt/esphome-victron_ble#72]
Hi Fabian,
thanks for your contributions, I would like to ask, if its possible to add pv panels values of voltage and current into victron ble communications? Thx Ondrej

**Comment by Fabian-Schmidt** [comment]
Please ask Victron to add this information to the Bluetooth advertising messages sent by the devices.

Currently I expose all data the advertising message frame contains.

Victron uses the Bluetooth advertising messages in the app for the overview page and as they don't display PV voltage there they are not sent it.

**Comment by ondrej0402** [comment]
And these messages are not the same like victron send it from device?
Because mppt voltage and current are visible in the victron app, connected
by bluetooth.
Thanks for answer

Dňa ut 5. 11. 2024 o 10:48 Fabian ***@***.***> napísala(a):

**Comment by Fabian-Schmidt** [comment]
The messages are the same as displayed in the overview page of the app.

When connecting to a device different messages are used.

**Comment by Bloodcarver** [comment]
![Screenshot_2024-12-03-19-42-39-788_com victronenergy victronconnect~2](https://github.com/user-attachments/assets/7ffee7f7-c468-449a-a02e-b06e5b10064d)
![Screenshot_2024-12-03-19-44-07-033_io homeassistant companion android~2](https://github.com/user-attachments/assets/ca6a4c06-8a7a-4ff2-84f8-7ae00d9fc0e8)

I dont understand, the value from bluetooth application do not match the value from  victron-ble.
Look at the attached images.

**Comment by Fabian-Schmidt** [comment]
The mppt device only transmits the battery (output) voltage and not the solar panel voltage.

It is the same values you can see in the app on the overview page, before you connect to the device.

**Comment by ondrej0402** [comment]
Your solarpanel spannung use device battery voltage in yaml, you have same value.

**Comment by Bloodcarver** [comment]
So a template thats devide PV_POWER with BATTERY_CURRENT wont work to get PV_VOLTAGE?

I need PV_CURRENT and PV_VOLTAGE wich is not present in the Victron bluetooth communication then )c:

**Comment by ondrej0402** [comment]
You have two possibilities:
1. recommendation from Fabian ask victron to publish these message's in BLE
2. Use esp mini and connect it to ve.direct port and read it.

**Comment by Bloodcarver** [comment]
Thanks I will give ve.direct a try. <3
