### ISSUE TITLE
Additional Sensors

### ISSUE THREAD

**Issue by steeks81** [Fabian-Schmidt/esphome-victron_ble#73]
Hi,
I have this up and running, and it is working great!

However wondering if it is posssible to read some additional sensors.  I've been looking at the project that uses the VE.Direct instead of bluetooth (https://github.com/KinDR007/VictronMPPT-ESPHOME/tree/main?tab=readme-ov-file)

And would like to see if some of the sensors such as below are available:
- yield_total/yesterday/max_power_today (Solar Charger)
- for SmartShunt:
H1 | depth_of_the_deepest_discharge
H2 | depth_of_the_last_discharge
H3 | depth_of_the_average_discharge
H4 | number_of_charge_cycles
H5 | number_of_full_discharges
H6 | cumulative_amp_hours_drawn
H7 | min_battery_voltage
H8 | max_battery_voltage
H9 | last_full_charge
H10 | number_of_automatic_synchronizations
H11 | number_of_low_main_voltage_alarms
H12 | number_of_high_main_voltage_alarms
H13 | number_of_low_auxiliary_voltage_alarms
H14 | number_of_high_auxiliary_voltage_alarms
H15 | min_auxiliary_battery_voltage
H16 | max_auxiliary_battery_voltage
H17 | amount_of_discharged_energy
H18 | amount_of_charged_energy

for e.g.

Maybe not all of these are available over bluetooth? But certainly things like charge cycles, depth of discharge/last full charge etc are all visiable on the victron connect app.
Would much rather use bluetooth if possible so can handle multiple devices (solar mptt+smartshunt) with 1 esp!

Thanks again for your hard work on this project!

**Comment by Fabian-Schmidt** [comment]
Hi,

I am already exporting all available sensor fields.

The Victron advertising/announcement protocol does not contain these fields.

I get the same fields which you can see in the Victron app on the **Overview** page.

See [Victron Community](https://community.victronenergy.com/questions/187303/victron-bluetooth-advertising-protocol.html) for details of the Victron Bluetooth advertising protocol and to ask Victron to include these information.
