### ISSUE TITLE
Info from Orion-Tr Smart DC-DC Charger

### ISSUE THREAD

**Issue by Th3M1k3y** [Fabian-Schmidt/esphome-victron_ble#78]
I have been using this component for some month with a smartshunt, and it has been working great.

Now I got [a 24v to 12v charger](https://www.victronenergy.com/dc-dc-converters/orion-tr-smart) for the battery for my diesel heater. I can see it in the Connect app, but I don't see it on the compatible list. Is it possible to add it, or do you need more info about it?

**Comment by HBK1** [comment]
Have you tried below config for DCDC:
https://github.com/Fabian-Schmidt/esphome-victron_ble/issues/20

**Comment by Th3M1k3y** [comment]
> Have you tried below config for DCDC: #20

That worked! :)
