### ISSUE TITLE
BatMon HomeAssistant-Integration

### ISSUE THREAD

**Issue by snipah** [Fabian-Schmidt/esphome-victron_ble#8]
Hi Fabian! 

Kurze Frage: Ich bin zufällig auf batmon gestoßen. Leider erfolgt der Connect zum Shunt nur sehr unzuverlässig, was mir aber gut gefallen hat, war die Integration in das Energy Dashboard des Home Assistant.

Wäre es möglich, das in ähnlicher Form in deine Implementierung einzubauen?

[https://github.com/fl4p/batmon-ha](url)

**Comment by Fabian-Schmidt** [comment]
Wie wird das batmon-ha in das Energy Dashboard eingebunden?
Ich sehe keine Hinweise in der Readme oder dem quellcode.

**Comment by snipah** [comment]
Batmon implements energy metering by integrating the power values from the BMS with the trapezoidal rule. You can add theses meters to your Home Assistant Energy Dashboard. The accuracy depends on the accuracy of the voltage and current readings from the BMS. Consider these having an error of 2~5%. Some BMS do not detect small currents (<200mA) and can miss high frequency peaks, leading to even greater error.

Total Energy Discharge Meter: total Energy out of the battery (increasing only, use this for the Energy Dashboard)
Total Energy Charge: total Energy into the battery (increasing only, use this for the Energy Dashboard)
Total Energy: The total energy flow into and out of the battery (decreasing and increasing). This equals to (Total Energy Charge) - (Total Energy Discharge).
Total Cycles: Total full cycles of the battery. One complete discharge and charge is a full cycle: SoC 100%-0%-100%. This is not a value provided by the BMS, but Batmon computes this by differentiating the SoC (e.g. integrate(abs(diff(SoC% / 100 / 2)))).

**Comment by snipah** [comment]
Ok. I agree!
